CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE refresh_tokens (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  token UUID DEFAULT UUID_GENERATE_V4() NOT NULL,
  expires_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL '101 days' NOT NULL,
  user_id BIGINT REFERENCES users (id)
);
